name: ðŸ¦… Sync to Gitlab

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  gitlab:
    runs-on: ubuntu-latest
    name: Ping
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync
        uses: offensive-vk/auto-repo-sync@master
        with:
          target-url: https://gitlab.com/offensive-vk/github-mirror.git
          target-username: ${{ secrets.TARGET_USER }}
          target-token: ${{ secrets.TARGET_TOKEN }}
