name: âš¡ Bulk Issue Creator

on:
  workflow_dispatch:
    inputs:
      issue_count:
        description: 'Number of Issues'
        required: true
        default: '100'

jobs:
  job:
    runs-on: ubuntu-latest
    name: Job
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh -y

      - uses: actions/checkout@v5
      - name: Job
        run: |
          for i in $(seq 1 ${{ github.event.inputs.issue_count || 100 }}); do
            issue_number=$(gh issue create --title "Automated Issue by TheHamsterBot" --body "This is issue $i, created by Hamster [bot]." --label "automated,bot,hamster,issue" --assignee "TheHamsterBot")
            echo "Issue #$issue_number created."
            sleep 3
            gh issue close "$issue_number" --comment "Hamster [bot] - Closed This Issue."
            echo "Issue #$issue_number closed."
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
